name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        env:
          LASTFM_API_KEY: ${{env.LASTFM_API_KEY}} # Use the secret you defined
        run: |
          echo "LASTFM_API_KEY=${LASTFM_API_KEY}" >> $GITHUB_ENV
          echo "API key from secret: $LASTFM_API_KEY" # Add this line for debugging

      - name: Build and deploy # Replace this with your build and deploy steps
        run: |
          # Your build and deploy commands here
